services:
  app:
    build: .
    ports:
      - "5000:5000"
    command: npm run dev
    depends_on:
      - db

  db:
    image: postgres:16.2
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local
