services:
  app:
    build:
      context: .
      target: dev
    ports:
      - "5000:5000"
    command: npm run dev
    volumes:
      - .:/app # To monitor for changes
      - /app/node_modules # Volume for node_modules to prevent internalBinding errors
    depends_on:
      - db

  db:
    extends:
      file: docker-compose.base.yml
      service: db

volumes:
  db-data:
    driver: local
